name: Shopify CSV Updater

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (UTC)
  workflow_dispatch:  # Allows manual execution

jobs:
  update-shopify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download CSV from Google Drive
        run: |
          FILE_ID="1WD1nIzMX3ZwbEjFr4fpIjgeGS3VK6h0c"  # Your actual Google Drive File ID
          FILE_NAME="Shopify_Product_Catalog_Modified.csv"

          # Fetch file using Google Drive API
          wget --no-check-certificate "https://drive.google.com/uc?export=download&id=${FILE_ID}" -O ${FILE_NAME}

          # Verify if file downloaded
          if [ ! -f "$FILE_NAME" ]; then
            echo "❌ CSV file download failed!"
            exit 1
          fi
          echo "✅ CSV file downloaded successfully: $FILE_NAME"

      - name: Run CSV Processing Script
        run: python shopify_csv_updater.py

      - name: Commit & Push Updated CSV to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Shopify_Product_Catalog_Modified.csv
          git commit -m "🔄 Auto-update CSV from Google Drive"
          git push origin main

      - name: Deploy to Shopify
        run: |
          echo "🚀 Deploying CSV to Shopify..."
          python shopify_csv_updater.py  # Your Python script handling Shopify updates
